### ISSUE TITLE
Outdated README.md

### ISSUE THREAD

**Issue by ilseleal** [microsoftgraph/android-java-snippets-rest-sample#31]
Hello. I am trying to integrate an Android app with Microsoft Graph. I think that the Microsoft Snippets example is very helpful. However, I have noticed that the **information provided in README.md is outdated**. It seems that your project structure has had a lot of changes recently and the documentation does not reflect that. 

Here are some of the issues:

- In "Understand the Code" there is a reference to the "unifiedapi". However, in the actual project there is no actual "unifiedapi" model. In fact, if you click on the [unifiedapi](https://github.com/microsoftgraph/android-java-snippets-rest-sample/blob/master/unifiedapi)  link under "Modules in the Office 365 Android unified API snippets project", the link doesn't work. 

- Since the project structure has changed, none of the links to source files work in the following sections: "Snippet classes", "Microsoft Graph API service classes", "Authentication classes for Office 365 business accounts".

I think it is very important for this documentation to be updated. **Android developers** like me, that are getting started with integrating Microsoft Graph in their apps, **rely on this documentation**. 

Thank you very much in advance. 

Best regards,
--Ilse

**Comment by JohnAustin-MSFT** [comment]
Hi Ilse, I apologize for not seeing this issue sooner :-(.  I'll add a work item for my December sprint to get this taken care of.

**Comment by ilseleal** [comment]
Thank you :)

**Comment by jasonjoh** [comment]
Closing this PR as we are archiving this sample. Please see https://github.com/microsoftgraph/msgraph-training-android for an Android sample.
