### ISSUE TITLE
How to integrate this API to Intune Android App?

### ISSUE THREAD

**Issue by KiranKumar521** [microsoftgraph/android-java-snippets-rest-sample#35]
We have integrated Intune SDK for our Android App and would like to bypass the auth process and update a token for all URL's.

Note: The app will get the token from the ADAL while the user sign in to the App.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this sample. Please see https://github.com/microsoftgraph/msgraph-training-android for an Android sample.
